### ISSUE TITLE
Tensorflow compatibility issues - "AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'"

### ISSUE THREAD

**Issue by osbornep** [vincentberaud/Minecraft-Reinforcement-Learning#5]
Hi,

I am attempting to replicate your code but am having issues with the Tensorflow dependecy, namely with Tensorflow 2.0, many attributes were removed such as ".reset_default_graph()" and ".Sessions()" so the following error is returned:

> Traceback (most recent call last):
>  File "agent_visual.py", line 461, in <module>
>   tf.reset_default_graph()
>AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

The simple solution (found here: https://stackoverflow.com/questions/40782271/attributeerror-module-tensorflow-has-no-attribute-reset-default-graph) is to return Tensorflow to version 1.X.

However, this is causing more issues therefore wanted to confirm what version of Tensorflow was used for your work?

Alternatively, these attributes seem to have been replaced by tf.function but I am not familiar with Tensorflow enough to confirm this. Would this be suitable to update your work to Tensorflow 2.0 or have I missunderstood something?

https://www.tensorflow.org/tutorials/customization/performance

Thanks in advance
Phil

**Comment by ClementRomac** [comment]
Hi,

Indeed, we used tensorflow 1.12 during ou work.
I have not used tensorflow 2.0 yet, but I have seen there are some solutions to migrate from 1.x to 2.x.

First, you can try using the v1 compatible version with the following tensorflow import :
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

There is also a script that upgrades v1 code to v2 (https://www.tensorflow.org/guide/upgrade). As our code is in a jupyter notebook, we should, as I understand, use the http://tf2up.ml/ project. I should definetly take a look at that in the next days (I have done a quick test tonight but it is adding a lot of 'compat' instead of really upgrading the code). 
If you get any result before that please let me know.

Clément

**Comment by osbornep** [comment]
Hi Clément,

Thank you so much, I attempted the first method but was receiving more issue unfortunately but will attempt the second and update the code to v2 if possible. I will update my results here in case anyone has a similar problem.

Thanks
Phil

**Comment by osbornep** [comment]
For anyone else trying to replicate, I have managed to get it working by simply installing with Tensorflow version 1.12 and CUDA 9.0.

Thanks
